### ISSUE TITLE
bam index not found

### ISSUE THREAD

**Issue by webbchen** [eldariont/svim#20]
Dear developers

I've tried to run svim alignment with a coordinate-sorted nglmr bamfile which I'd indexed with samtools. The indices are in the same directory as the alignment files. At the genotyping stage an error informs me that no index was found, see log file content below. The same error occurs with my minimap alignments also. It does produce a vcf file with variants but no genotyping information for the sample.

(filenames and directories are anonymised)

```
2019-08-20 13:37:13,851 [INFO   ]  ****************** Start SVIM, version 1.2.0 ******************
2019-08-20 13:37:13,851 [INFO   ]  CMD: python3 /home/annew/.local/bin/svim alignment --min_sv_size 10 --minimum_depth 10 --sample sample . /scratch/alignments_to_ref/sample_nanopore_to_fungusref_n
gmlr.sorted.bam /scratch/alignments_to_ref/fungusref.fasta
2019-08-20 13:37:13,852 [INFO   ]  WORKING DIR: /workdir/sample_SVIM-calls_nglmr
2019-08-20 13:37:13,852 [INFO   ]  PARAMETER: del_ins_dup_max_distance, VALUE: 1.0
2019-08-20 13:37:13,852 [INFO   ]  PARAMETER: segment_overlap_tolerance, VALUE: 5
2019-08-20 13:37:13,852 [INFO   ]  PARAMETER: duplications_as_insertions, VALUE: False
2019-08-20 13:37:13,852 [INFO   ]  PARAMETER: distance_normalizer, VALUE: 900
2019-08-20 13:37:13,853 [INFO   ]  PARAMETER: segment_gap_tolerance, VALUE: 10
2019-08-20 13:37:13,853 [INFO   ]  PARAMETER: minimum_depth, VALUE: 10
2019-08-20 13:37:13,853 [INFO   ]  PARAMETER: homozygous_threshold, VALUE: 0.8
2019-08-20 13:37:13,853 [INFO   ]  PARAMETER: minimum_score, VALUE: 3
2019-08-20 13:37:13,853 [INFO   ]  PARAMETER: read_names, VALUE: False
2019-08-20 13:37:13,853 [INFO   ]  PARAMETER: sample, VALUE: sample
2019-08-20 13:37:13,853 [INFO   ]  PARAMETER: heterozygous_threshold, VALUE: 0.2
2019-08-20 13:37:13,854 [INFO   ]  PARAMETER: max_sv_size, VALUE: 100000
2019-08-20 13:37:13,854 [INFO   ]  PARAMETER: trans_sv_max_distance, VALUE: 500
2019-08-20 13:37:13,854 [INFO   ]  PARAMETER: min_mapq, VALUE: 20
2019-08-20 13:37:13,854 [INFO   ]  PARAMETER: partition_max_distance, VALUE: 5000
2019-08-20 13:37:13,854 [INFO   ]  PARAMETER: skip_genotyping, VALUE: False
2019-08-20 13:37:13,854 [INFO   ]  PARAMETER: sequence_alleles, VALUE: False
2019-08-20 13:37:13,855 [INFO   ]  PARAMETER: trans_destination_partition_max_distance, VALUE: 1000
2019-08-20 13:37:13,855 [INFO   ]  PARAMETER: cluster_max_distance, VALUE: 0.3
2019-08-20 13:37:13,855 [INFO   ]  PARAMETER: sub, VALUE: alignment
2019-08-20 13:37:13,855 [INFO   ]  PARAMETER: bam_file, VALUE: /scratch/alignments_to_ref/sample_nanopore_to_fungusref_ngmlr.sorted.bam
2019-08-20 13:37:13,855 [INFO   ]  PARAMETER: types, VALUE: DEL,INS,INV,DUP_TAN,DUP_INT,BND
2019-08-20 13:37:13,855 [INFO   ]  PARAMETER: working_dir, VALUE: /local/tmp/annew/sample_SVIM-calls_nglmr
2019-08-20 13:37:13,855 [INFO   ]  PARAMETER: insertion_sequences, VALUE: False
2019-08-20 13:37:13,856 [INFO   ]  PARAMETER: min_sv_size, VALUE: 10
2019-08-20 13:37:13,856 [INFO   ]  PARAMETER: genome, VALUE: /alignments_to_ref/fungusref.fasta
2019-08-20 13:37:13,856 [INFO   ]  PARAMETER: trans_partition_max_distance, VALUE: 200
2019-08-20 13:37:13,856 [INFO   ]  ****************** STEP 1: COLLECT ******************
2019-08-20 13:37:13,856 [INFO   ]  MODE: alignment
2019-08-20 13:37:13,856 [INFO   ]  INPUT: /scratch/alignments_to_ref/sample_nanopore_to_fungusref_ngmlr.sorted.bam
2019-08-20 13:37:15,281 [INFO   ]  Processed read 10000

(...)

2019-08-20 13:38:00,210 [INFO   ]  Processed read 450000
2019-08-20 13:38:02,670 [INFO   ]  Found 106970 signatures for deleted regions.
2019-08-20 13:38:02,671 [INFO   ]  Found 37542 signatures for inserted regions.
2019-08-20 13:38:02,671 [INFO   ]  Found 243 signatures for inverted regions.
2019-08-20 13:38:02,671 [INFO   ]  Found 698 signatures for tandem duplicated regions.
2019-08-20 13:38:02,671 [INFO   ]  Found 17433 signatures for translocation breakpoints.
2019-08-20 13:38:02,671 [INFO   ]  Found 116 signatures for inserted regions with detected region of origin.
2019-08-20 13:38:02,671 [INFO   ]  ****************** STEP 2: CLUSTER ******************
2019-08-20 13:38:09,548 [INFO   ]  Clustered deleted regions: 20332 partitions and 34426 clusters
2019-08-20 13:38:13,878 [INFO   ]  Clustered inserted regions: 4769 partitions and 6662 clusters
2019-08-20 13:38:14,528 [INFO   ]  Clustered inverted regions: 173 partitions and 175 clusters
2019-08-20 13:38:14,614 [INFO   ]  Clustered tandem duplicated regions: 203 partitions and 239 clusters
2019-08-20 13:38:14,645 [INFO   ]  Clustered inserted regions with detected region of origin: 14 partitions and 14 clusters
2019-08-20 13:38:14,683 [INFO   ]  Finished clustering. Writing signature clusters..
2019-08-20 13:38:15,385 [INFO   ]  ****************** STEP 3: COMBINE ******************
2019-08-20 13:38:15,386 [INFO   ]  Cluster translocation breakpoints..
2019-08-20 13:38:17,001 [INFO   ]  Combine inserted regions with translocation breakpoints..
2019-08-20 13:38:17,027 [INFO   ]  Create interspersed duplication candidates and flag cut&paste insertions..
2019-08-20 13:38:18,819 [INFO   ]  Cluster interspersed duplication candidates one more time..
2019-08-20 13:38:18,822 [INFO   ]  Clustered interspersed duplication candidates: 14 partitions and 15 clusters
2019-08-20 13:38:18,828 [INFO   ]  ****************** STEP 4: GENOTYPE ******************
2019-08-20 13:38:18,828 [INFO   ]  Genotyping deletions..
2019-08-20 13:38:18,828 [ERROR  ]  fetch called on bamfile without index
Traceback (most recent call last):
  File "/home/annew/.local/bin/svim", line 165, in <module>
    sys.exit(main())
  File "/home/annew/.local/bin/svim", line 126, in main
    genotype(deletion_candidates, aln_file, "DEL", options)
  File "/home/annew/.local/lib/python3.5/site-packages/svim/SVIM_genotyping.py", line 49, in genotype
    alignment_it = bam.fetch(contig=contig, start=max(0, start-1000), stop=min(contig_length, end+1000))
  File "pysam/libcalignmentfile.pyx", line 1088, in pysam.libcalignmentfile.AlignmentFile.fetch
ValueError: fetch called on bamfile without index

```

Kind regards,

A. Webb

**Comment by eldariont** [comment]
Hi Anne,

thanks for reporting this issue. The exception is raised by the pysam library which complains about a missing bam index file with a `.bai` ending.
You write that you indexed the bam file with samtools. Does that mean there exists a file called `/scratch/alignments_to_ref/sample_nanopore_to_fungusref_ngmlr.sorted.bam.bai`? If yes, you could try removing and regenerating it with `samtools index /scratch/alignments_to_ref/sample_nanopore_to_fungusref_ngmlr.sorted.bam`.

Please let me know if that helps. If not we need to continue searching for the reason of the mysterious exception.

Best regards
David

**Comment by webbchen** [comment]
Hi David
 The *.bai files exist and I have also tried re-indexing the *.bam fles with samtools as suggested. The problem persists.

Kind regards,

Anne

**Comment by eldariont** [comment]
Hi Anne,

thanks for checking. That is very strange indeed. Could you try fetching reads from the bam file using pysam directly like this (you need to replace `chr1` with one of the contig names in your file):
```
import pysam
bamfile = pysam.AlignmentFile("/scratch/alignments_to_ref/sample_nanopore_to_fungusref_ngmlr.sorted.bam", "r")
iter = bamfile.fetch("chr1", 1, 100000)
len(list(iter))
```

If this causes the same exception, pysam is unable to open your bam file or bam index for some reason. How did you install SVIM (and pysam)?

Best regards
David

**Comment by webbchen** [comment]
Hi David
It seems that my indices had been corrupted. Re-indexed and now it works fine. Sorry for the confusion.

Many thanks,
Anne

**Comment by eldariont** [comment]
Hi Anne,
I'm glad to hear you found a solution.
Thanks for letting me know.
David
