### ISSUE TITLE
SVIM breaks with OSError: truncated file in Genotyping step

### ISSUE THREAD

**Issue by caspargross** [eldariont/svim#30]
I have one bamfile for which svim repeatedly fails with the following error message:
```
2020-02-27 21:09:20,651 [INFO   ]  ****************** STEP 3: COMBINE ******************
2020-02-27 21:09:20,684 [INFO   ]  Cluster translocation breakpoints..
2020-02-27 21:09:25,173 [INFO   ]  Combine inserted regions with translocation breakpoints..
2020-02-27 21:09:25,720 [INFO   ]  Create interspersed duplication candidates and flag cut&paste insertions..
2020-02-27 21:12:28,804 [INFO   ]  Cluster interspersed duplication candidates one more time..
2020-02-27 21:12:28,809 [INFO   ]  Clustered interspersed duplication candidates: 26 partitions and 27 clusters
2020-02-27 21:12:28,844 [INFO   ]  ****************** STEP 4: GENOTYPE ******************
2020-02-27 21:12:28,844 [INFO   ]  Genotyping deletions..
2020-02-27 21:12:28,859 [ERROR  ]  truncated file
Traceback (most recent call last):
  File "/mnt/SRV018/projects/external/promethion/sv_lr_svim/venv/bin/svim", line 165, in <module>
    sys.exit(main())
  File "/mnt/SRV018/projects/external/promethion/sv_lr_svim/venv/bin/svim", line 126, in main
    genotype(deletion_candidates, aln_file, "DEL", options)
  File "/mnt/SRV018/projects/external/promethion/sv_lr_svim/venv/lib/python3.7/site-packages/svim/SVIM_genotyping.py", line 58, in genotype
    current_alignment = next(alignment_it)
  File "pysam/libcalignmentfile.pyx", line 2092, in pysam.libcalignmentfile.IteratorRowRegion.__next__
OSError: truncated file
```

To me this appears to be a problem with the input data, however other analysis on the same bamfile worked without problems and samtools quickcheck reports no issues with the file. Also it is strange that svim fails at such a late stage, after analysing the whole file. Do you have an idea what might cause the problem? 

I am using a venv with python 3.7.3, pysam 0.15.3 and svim 1.2.0

**Comment by eldariont** [comment]
Hi Caspar,
thanks for reporting this issue. When SVIM first analyzes a BAM file it iterates through it from start to end. This seems to have worked without any problem. In the genotyping stage, SVIM specifically fetches reads for each SV region and uses the BAM index for this. The simplest explanation for the error would be that this index is somehow broken.
Can you try to remove the .bam.bai file and regenerate it with `samtools index <bam>`?
Best
David

**Comment by caspargross** [comment]
Thanks! That solved the problem.
