### ISSUE TITLE
Check existence of bam index upfront

### ISSUE THREAD

**Issue by SHuang-Broad** [eldariont/svim#33]
I forgot to index my BAM (my mistake, too eager to get to the variants...) and fed it to SVIM.

SVIM happily accepted the BAM, but ultimately errored out 

```
2020-04-01 17:28:51,738 [INFO   ]  ****************** STEP 3: COMBINE ******************
2020-04-01 17:28:51,767 [INFO   ]  Cluster translocation breakpoints..
2020-04-01 17:28:53,830 [INFO   ]  Combine inserted regions with translocation breakpoints..
2020-04-01 17:28:55,566 [INFO   ]  Create interspersed duplication candidates and flag cut&paste insertions..
2020-04-01 17:29:19,039 [INFO   ]  Cluster interspersed duplication candidates one more time..
2020-04-01 17:29:19,042 [INFO   ]  Clustered interspersed duplication candidates: 59 partitions and 70 clusters
2020-04-01 17:29:19,061 [INFO   ]  ****************** STEP 4: GENOTYPE ******************
2020-04-01 17:29:19,062 [INFO   ]  Genotyping deletions..
2020-04-01 17:29:19,062 [ERROR  ]  fetch called on bamfile without index
Traceback (most recent call last):
  File "/home/shuang/miniconda3/envs/svim/bin/svim", line 165, in <module>
    sys.exit(main())
  File "/home/shuang/miniconda3/envs/svim/bin/svim", line 126, in main
    genotype(deletion_candidates, aln_file, "DEL", options)
  File "/home/shuang/miniconda3/envs/svim/lib/python3.7/site-packages/svim/SVIM_genotyping.py", line 49, in genotype
    alignment_it = bam.fetch(contig=contig, start=max(0, start-1000), stop=min(contig_length, end+1000))
  File "pysam/libcalignmentfile.pyx", line 1092, in pysam.libcalignmentfile.AlignmentFile.fetch
ValueError: fetch called on bamfile without index
```

It would be nice to check the existence of the index file (*.bam.bai and/or *.bai) upfront to save sometime.

Thanks!
Steve

**Comment by eldariont** [comment]
Thanks, Steve, for this good suggestion! I added an additional check for a valid index before the actual analysis begins (6516806a7af0c36ec56667b0a2506aa6bab44cde). If the index is missing, SVIM now prints a warning but continues without genotyping.
