### ISSUE TITLE
svim2.0.0 err

### ISSUE THREAD

**Issue by vegetableyu** [eldariont/svim#70]
Hi，
i am using svim2.0.0 and encountered an err:
[ERROR  ]  '<' not supported between instances of 'NoneType' and 'str'
Traceback (most recent call last):
  File "/miniconda3/envs/svcaller/bin/svim", line 221, in <module>
    sys.exit(main())
  File "/miniconda3/envs/svcaller/bin/svim", line 132, in main
    signature_clusters = cluster_sv_signatures(sv_signatures, options)
  File "/miniconda3/envs/svcaller/lib/python3.9/site-packages/svim/SVIM_CLUSTER.py", line 19, in cluster_sv_signatures
    deletion_signature_clusters = partition_and_cluster(deletion_signatures, options, "deleted regions")
  File "/miniconda3/envs/svcaller/lib/python3.9/site-packages/svim/SVIM_clustering.py", line 376, in partition_and_cluster
    partitions = form_partitions(signatures, options.partition_max_distance)
  File "/miniconda3/envs/svcaller/lib/python3.9/site-packages/svim/SVIM_clustering.py", line 19, in form_partitions
    sorted_signatures = sorted(sv_signatures, key=lambda evi: evi.get_key())
TypeError: '<' not supported between instances of 'NoneType' and 'str'

The command is : svim alignment --min_sv_size 50 --sample {sample}  {inputbam}  {inputfa}

Look forward to your kind reply.
YU

**Comment by patricksis** [comment]
hey @vegetableyu did you find a solution to this?
